language: node_js
node_js:
 - lts/*

sudo: required
os: linux
dist: trusty

before_install:
 - sudo apt update
 - sudo apt-get install google-chrome-stable

install:
  - cd app
  - npm install

script:
- npm test
