language: node_js
node_js:
 - "10"

notifications:
 email: false

sudo: required
os: linux
dist: trusty

install:
 - cd app
 - npm install
 - npm start &

script:
 - npm run test-unit
 - npm run travis
