language: node_js
node_js:
 - "10"

notifications:
 email: false

sudo: required
os: linux
dist: trusty

addons:
  sonarcloud:
    organization: "loanngio-github"

install: true

script:
 - sonar-scanner -Dsonar.login=${SONAR_TOKEN}
 - cd app
 - npm install
 - npm start &
 - npm run test-unit
 - npm run travis
